[package]
name = "daemon"
version.workspace = true
edition.workspace = true

[dependencies]
shared-core = { path = "../shared-core" }
shared-service = { path = "../shared-service" }

anyhow = { workspace = true }
futures = { workspace = true }
png = { workspace = true }
serde = { workspace = true, features = ["derive"] }
sqlx = { workspace = true, features = ["runtime-tokio", "sqlite"] }
tracing = { workspace = true }
tray-item = { workspace = true, features = ["ksni"] }
tokio = { workspace = true, features = ["fs", "macros", "rt-multi-thread", "time", "signal", "sync"] }
tokio-util = { workspace = true, features = ["rt"] }
prost = { workspace = true }
tonic = { workspace = true }
tonic-prost = { workspace = true }
